# Generated by Django 4.0.5 on 2022-06-26 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandwichIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BREAD', '빵'), ('TOPING', '토핑'), ('CHEEZE', '치즈'), ('SOURCE', '소스')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('remain_cnt', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('reg_dtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_dtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SandwichOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandwich_no', models.PositiveIntegerField()),
                ('ingredient_type', models.CharField(max_length=50)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('is_delete', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sandwich_no'],
            },
        ),
    ]
